// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

export default defineConfig({
  site: 'https://citizen-infra.netlify.app',
  integrations: [
    starlight({
      title: 'Citizen Infrastructure',
      description:
        'A free, public resource for citizens: what citizen infrastructure is, and a practical toolkit of things citizens can use to act together.',
      editLink: {
        baseUrl: 'https://github.com/Citizen-Infra/wiki/edit/main/',
      },
      lastUpdated: true,
      pagefind: true,
      social: [
        { icon: 'github', label: 'GitHub', href: 'https://github.com/Citizen-Infra/wiki' },
      ],
      sidebar: [
        { label: 'Start here', items: [
          { slug: 'start/what-is-citizen-infrastructure' },
          { slug: 'start/how-to-use-this-resource' },
        ]},
        { label: 'The idea', items: [
          { slug: 'idea/technology-for-collective-action' },
          { slug: 'idea/digital-pitchforks' },
        ]},
        { label: 'Concepts', items: [
          { slug: 'concepts/overview' },
          { label: 'Deliberative democracy', collapsed: true, items: [
            { slug: 'concepts/open-democracy' },
            { slug: 'concepts/citizens-assembly' },
            { slug: 'concepts/running-a-citizens-assembly' },
            { slug: 'concepts/deliberative-polling' },
            { slug: 'concepts/epistemic-democracy' },
            { slug: 'concepts/pre-bunking' },
            { slug: 'concepts/sortition' },
            { slug: 'concepts/peoples-branch' },
            { slug: 'concepts/citizen-governance-of-assemblies' },
            { slug: 'concepts/civic-love' },
            { slug: 'concepts/binding-vs-advisory' },
            { slug: 'concepts/institutionalising-deliberation' },
            { slug: 'concepts/scaling-catalysts' },
            { slug: 'concepts/investor-assemblies' },
            { slug: 'concepts/democratising-finance' },
            { slug: 'concepts/sortition-in-organisations' },
            { slug: 'concepts/children-and-youth-assemblies' },
            { slug: 'concepts/intergenerational-deliberation' },
            { slug: 'concepts/deliberation-and-enfranchisement' },
          ]},
          { label: 'Self-governance & power', collapsed: true, items: [
            { slug: 'concepts/commoning-standard' },
            { slug: 'concepts/power-matrix' },
            { slug: 'concepts/cargo-cult-democracy' },
            { slug: 'concepts/tech-place-is-education' },
            { slug: 'concepts/funding-the-commons' },
            { slug: 'concepts/plural-mechanisms' },
            { slug: 'concepts/network-societies' },
          ]},
          { label: 'The commons', collapsed: true, items: [
            { slug: 'concepts/the-commons' },
            { slug: 'concepts/enclosure' },
            { slug: 'concepts/the-ontoshift' },
            { slug: 'concepts/relational-property' },
            { slug: 'concepts/parallel-polis' },
          ]},
          { label: 'Online communities & governance', collapsed: true, items: [
            { slug: 'concepts/implicit-feudalism' },
            { slug: 'concepts/modular-politics' },
            { slug: 'concepts/constitutional-agents' },
            { slug: 'concepts/protocol' },
            { slug: 'concepts/bridging-and-pro-social-media' },
          ]},
          { label: 'Civic AI', collapsed: true, items: [
            { slug: 'concepts/plurality' },
            { slug: 'concepts/civic-ai' },
            { slug: 'concepts/democratising-ai' },
            { slug: 'concepts/public-ai' },
            { slug: 'concepts/does-ai-weaken-institutions' },
            { slug: 'concepts/ai-for-participation' },
            { slug: 'concepts/synthetic-participation' },
            { slug: 'concepts/ai-and-deliberation' },
            { slug: 'concepts/scaling-deliberation' },
            { slug: 'concepts/habermas-machine' },
            { slug: 'concepts/ai-reflectors' },
            { slug: 'concepts/argument-mapping' },
            { slug: 'concepts/civic-listening' },
            { slug: 'concepts/conversation-networks' },
            { slug: 'concepts/uncommon-ground' },
          ]},
          { label: 'The civic tech field', collapsed: true, items: [
            { slug: 'concepts/why-civic-tech-fails' },
            { slug: 'concepts/civic-products-and-features' },
            { slug: 'concepts/interoperability-and-standards' },
            { slug: 'concepts/organizer-kit' },
            { slug: 'concepts/decentralized-landscape' },
            { slug: 'concepts/civic-intelligence-infrastructure' },
            { slug: 'concepts/relational-tech' },
            { slug: 'concepts/locality-to-locality-spreading' },
          ]},
          { label: 'The bigger picture', collapsed: true, items: [
            { slug: 'concepts/metacrisis' },
            { slug: 'concepts/planetary-governance' },
            { slug: 'concepts/segmented-sovereignty' },
            { slug: 'concepts/multispecies-governance' },
          ]},
        ]},
        { label: 'The toolkit', items: [
          { slug: 'toolkit/overview' },
          { slug: 'toolkit/connect-with-neighbors' },
          { slug: 'toolkit/coordinate-a-community' },
          { slug: 'toolkit/decide-together' },
          { slug: 'toolkit/share-culture-and-resources' },
          { slug: 'toolkit/fund-collective-work' },
        ]},
        { label: 'Run Reports', items: [
          { slug: 'run-reports/overview' },
          { label: "Citizens' assemblies & conventions", collapsed: true, items: [
            { slug: 'run-reports/irish-citizens-assembly' },
            { slug: 'run-reports/america-in-one-room' },
            { slug: 'run-reports/deschutes-youth-homelessness' },
            { slug: 'run-reports/french-great-national-debate' },
            { slug: 'run-reports/french-convention-end-of-life' },
            { slug: 'run-reports/french-convention-climate' },
            { slug: 'run-reports/austrian-climate-assembly' },
            { slug: 'run-reports/norway-future-panel' },
            { slug: 'run-reports/birmingham-museums-jury' },
            { slug: 'run-reports/global-assembly-2021' },
            { slug: 'run-reports/connecticut-property-taxes' },
            { slug: 'run-reports/la-city-charter-assembly' },
            { slug: 'run-reports/lexington-civic-assembly' },
            { slug: 'run-reports/ukraine-wartime-assemblies' },
            { slug: 'run-reports/manchester-peoples-panel-ai' },
          ]},
          { label: 'Constitutional & electoral reform', collapsed: true, items: [
            { slug: 'run-reports/iceland-2010-constitution' },
            { slug: 'run-reports/michigan-redistricting-commission' },
          ]},
          { label: 'Permanent & recurring models', collapsed: true, items: [
            { slug: 'run-reports/ostbelgien-citizens-council' },
            { slug: 'run-reports/demos-waves' },
          ]},
          { label: 'Children & young people', collapsed: true, items: [
            { slug: 'run-reports/ireland-biodiversity-assembly' },
            { slug: 'run-reports/scotland-climate-children' },
          ]},
          { label: 'Digital & AI-facilitated deliberation', collapsed: true, items: [
            { slug: 'run-reports/vtaiwan-uber' },
            { slug: 'run-reports/taiwan-alignment-assemblies' },
            { slug: 'run-reports/engaged-california' },
            { slug: 'run-reports/bowling-green-what-could-bg-be' },
            { slug: 'run-reports/anno-tokyo-2024' },
          ]},
        ]},
        { label: 'Stories', items: [
          { slug: 'stories/overview' },
          { slug: 'stories/topanga-fire-mutual-aid' },
          { slug: 'stories/open-source-insulin' },
          { slug: 'stories/fureai-kippu' },
          { slug: 'stories/american-conversation-project' },
          { slug: 'stories/real-talk-for-change' },
          { slug: 'stories/embassy-of-the-north-sea' },
          { slug: 'stories/interspecies-money' },
          { slug: 'stories/outer-sunset' },
          { slug: 'stories/community-supplies' },
        ]},
        { label: 'Ecosystem', items: [
          { slug: 'ecosystem/overview' },
        ]},
        { label: 'Library', items: [
          { slug: 'library/portable-governance' },
          { slug: 'library/reading-and-sources' },
        ]},
        { label: 'About', items: [
          { slug: 'about' },
        ]},
      ],
    }),
  ],
});
